#!/usr/bin/env bash
#
# Runs every query in sql/ in order, writes the ones that return rows to
# results/<basename>.csv, and records what each one cost in results/run_log.md.
#
#   BQ_PROJECT=your-project-id ./scripts/run_queries.sh
#   BQ_PROJECT=your-project-id ./scripts/run_queries.sh sql/02_tag_approval/22_tag_rankings.sql
#
# The build scripts (every file whose first statement is CREATE) write tables
# into a dataset in your own project — `so_analysis`, or whatever BQ_DATASET
# says. Create it first:
#   bq --location=US mk --dataset "$BQ_PROJECT:so_analysis"
#
# Files run in path order, and path order is dependency order: 00_profiling
# reads only the public tables, 01_cohort builds the materialized tables, and
# everything after that reads them. Running a single file assumes the tables it
# needs already exist; it leaves run_log.md untouched.
#
# Notes:
#   * Queries are piped in on stdin rather than passed as an argument. The files
#     start with `--` comment lines, and bq would otherwise try to parse the
#     first one as a command-line flag.
#   * Outputs go to a temporary file and are moved into results/ only when the
#     query succeeds, so a failure never leaves a committed file half-written.
#   * Every job gets its own id, so its cost is read back from that job rather
#     than from "the most recent job in the project".

set -euo pipefail

PROJECT="${BQ_PROJECT:?Set BQ_PROJECT to your Google Cloud project id}"
DATASET="${BQ_DATASET:-so_analysis}"
MAX_BYTES="${MAX_BYTES:-60000000000}"   # 60 GB ceiling per query; the cohort build is the only one near it
MAX_ROWS="${MAX_ROWS:-2000}"            # the full eligible-tag list is the widest output
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOG="$ROOT/results/run_log.md"

command -v bq > /dev/null || { echo "bq (Google Cloud SDK) is required" >&2; exit 1; }
command -v jq > /dev/null || { echo "jq is required" >&2; exit 1; }

if ! bq --project_id="$PROJECT" show --format=none "$PROJECT:$DATASET" > /dev/null 2>&1; then
  echo "Dataset $PROJECT:$DATASET does not exist. Create it first:" >&2
  echo "  bq --location=US mk --dataset \"$PROJECT:$DATASET\"" >&2
  exit 1
fi

files=("$@")
full_run=0
if [ ${#files[@]} -eq 0 ]; then
  full_run=1
  while IFS= read -r line; do files+=("$line"); done < <(find "$ROOT/sql" -name '*.sql' | sort)
fi

gb() { awk -v b="${1:-0}" 'BEGIN { printf "%.2f", b / 1073741824 }'; }

log_rows=()
total_bytes=0
materialized_only=0
for f in "${files[@]}"; do
  name="$(basename "${f%.sql}")"
  rel="${f#"$ROOT"/}"

  # Dry runs are free and are never served from cache, so they give the cold-run
  # figure whether or not the query has run before. bq reports a broken query
  # on stdout as plain text, so the output is checked before it is parsed.
  dry_run="$(bq --project_id="$PROJECT" --format=json query --use_legacy_sql=false --dry_run < "$f" 2>&1)" \
    || { echo "dry run failed: ${rel}" >&2; printf '%s\n' "$dry_run" >&2; exit 1; }
  scanned="$(printf '%s' "$dry_run" | jq -r '.statistics.query.totalBytesProcessed // "0"' 2> /dev/null)" \
    || { echo "dry run failed: ${rel}" >&2; printf '%s\n' "$dry_run" >&2; exit 1; }

  job="run_${name}_$(date +%Y%m%d%H%M%S)_${RANDOM}"
  first_statement="$(grep -m1 -vE '^\s*(--|$)' "$f" || true)"
  if grep -qiE '^\s*CREATE' <<< "$first_statement"; then
    # Builds a table: run it, no CSV to capture.
    bq --project_id="$PROJECT" --quiet query --use_legacy_sql=false \
       --job_id="$job" --maximum_bytes_billed="$MAX_BYTES" < "$f" > /dev/null
    rows="-"
    out="table"
  else
    tmp="$(mktemp)"
    bq --project_id="$PROJECT" --quiet --format=csv query --use_legacy_sql=false \
       --job_id="$job" --max_rows="$MAX_ROWS" --maximum_bytes_billed="$MAX_BYTES" < "$f" > "$tmp"
    mv "$tmp" "$ROOT/results/${name}.csv"
    rows=$(( $(wc -l < "$ROOT/results/${name}.csv") - 1 ))
    out="results/${name}.csv"
  fi

  if [ "$scanned" = "0" ]; then
    scanned="$(bq --project_id="$PROJECT" --format=json show -j "$job" \
               | jq -r '.statistics.query.totalBytesProcessed // "0"')"
  fi
  total_bytes=$(( total_bytes + scanned ))
  grep -q 'bigquery-public-data' "$f" || materialized_only=$(( materialized_only + 1 ))
  log_rows+=("| \`${rel}\` | $(gb "$scanned") | ${rows} | ${out} |")
  echo "ok  ${rel}  $(gb "$scanned") GB"
done

if [ "$full_run" -eq 1 ]; then
  {
    echo "# Query run log"
    echo
    echo "Regenerated by \`scripts/run_queries.sh\` on $(date -u +%Y-%m-%d) (UTC)."
    echo
    echo "\"GB scanned\" is what a cold run reads, from BigQuery's dry-run estimator."
    echo "Re-running an unchanged query bills zero because BigQuery serves it from"
    echo "cache, so billed bytes would understate what this analysis costs someone"
    echo "running it for the first time. The scanned figure is the one worth reporting."
    echo
    echo "| query | GB scanned | rows | output |"
    echo "|---|---|---|---|"
    printf '%s\n' "${log_rows[@]}"
    echo "| | **$(gb "$total_bytes")** | | |"
    echo
    echo "The BigQuery sandbox allows 1024 GB of query processing per month."
    echo
    echo "${materialized_only} of ${#files[@]} queries read only the materialized tables in"
    echo "\`${DATASET}\`. The rest touch the public source, and only the cohort build reads"
    echo "\`posts_questions.body\`, which holds roughly three quarters of that table's bytes."
    echo "Reading it once and materializing the derived features is what keeps everything"
    echo "downstream in the megabytes."
  } > "$LOG"
fi

echo "total: $(gb "$total_bytes") GB"
