#!/usr/bin/env bash
#
# Runs every query in sql/ in order, writes the ones that return rows to
# results/<basename>.csv, and records what each one cost in results/run_log.md.
#
#   BQ_PROJECT=your-project-id ./scripts/run_queries.sh
#   BQ_PROJECT=your-project-id ./scripts/run_queries.sh sql/02_tag_approval/21_tag_rankings.sql
#
# The build scripts under sql/01_cohort/ write tables into a dataset called
# `so_analysis` in your own project; create it first with:
#   bq --location=US mk --dataset "$BQ_PROJECT:so_analysis"
#
# Note: queries are piped in on stdin rather than passed as an argument. The
# files start with `--` comment lines, and bq would otherwise try to parse the
# first one as a command-line flag.

set -euo pipefail

PROJECT="${BQ_PROJECT:?Set BQ_PROJECT to your Google Cloud project id}"
MAX_BYTES="${MAX_BYTES:-60000000000}"   # 60 GB ceiling; the cohort build is the only query that approaches it
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOG="$ROOT/results/run_log.md"

files=("$@")
if [ ${#files[@]} -eq 0 ]; then
  while IFS= read -r line; do files+=("$line"); done < <(find "$ROOT/sql" -name '*.sql' | sort)
fi

{
  echo "# Query run log"
  echo
  echo "Regenerated by \`scripts/run_queries.sh\`. Bytes are what BigQuery actually"
  echo "billed, read back from the job after each run — not an estimate."
  echo
  echo "| query | GB billed | rows | output |"
  echo "|---|---|---|---|"
} > "$LOG"

total=0
for f in "${files[@]}"; do
  name="$(basename "${f%.sql}")"
  rel="${f#"$ROOT"/}"

  if grep -qiE '^\s*(CREATE|DECLARE)' "$f"; then
    # Builds a table: run it, no CSV to capture.
    bq --project_id="$PROJECT" query --use_legacy_sql=false \
       --maximum_bytes_billed="$MAX_BYTES" < "$f" > /dev/null
    rows="-"
    out="table"
  else
    bq --project_id="$PROJECT" --format=csv query --use_legacy_sql=false \
       --max_rows=500 --maximum_bytes_billed="$MAX_BYTES" < "$f" \
       > "$ROOT/results/${name}.csv"
    rows=$(( $(wc -l < "$ROOT/results/${name}.csv") - 1 ))
    out="results/${name}.csv"
  fi

  bytes=$(bq --project_id="$PROJECT" --format=json ls -j -n 1 2>/dev/null \
          | /usr/bin/jq -r '.[0].statistics.query.totalBytesBilled // .[0].statistics.totalBytesProcessed // "0"')
  gb=$(awk "BEGIN{printf \"%.2f\", ${bytes:-0}/1073741824}")
  total=$(awk "BEGIN{printf \"%.2f\", $total + $gb}")

  printf '| `%s` | %s | %s | %s |\n' "$rel" "$gb" "$rows" "$out" >> "$LOG"
  echo "ok  $rel  ${gb} GB"
done

{
  echo "| | **${total}** | | |"
  echo
  echo "The BigQuery sandbox allows 1024 GB of query processing per month."
  echo
  echo "Almost all of the total is a single query: \`sql/01_cohort/10_build_question_cohort.sql\`,"
  echo "which is the only one that reads \`posts_questions.body\`. That column holds"
  echo "roughly three quarters of the table's bytes. Reading it once and materialising"
  echo "the derived features is what keeps every other query in this repository under"
  echo "a gigabyte."
} >> "$LOG"

echo "total: ${total} GB"
